import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Clock, Maximize, Moon, NotebookTabs, RotateCcw } from 'lucide-react';
import { useEffect, useState } from 'react';
import ThreeScene from './components/ThreeScene';
import { Card, MoneyBars, QR } from './components/widgets';
import { annexSlides, mainSlides, Slide } from './data/presentationContent';
const fmt=(n:number)=>`€${n.toLocaleString('en-US')}`;
function ProgressBar({i,total}:{i:number;total:number}){return <div className="fixed bottom-0 left-0 h-1 bg-[#00A86B] z-40" style={{width:`${((i+1)/total)*100}%`}}/>}
function Timer(){const[s,setS]=useState(0);useEffect(()=>{const t=setInterval(()=>setS(x=>x+1),1000);return()=>clearInterval(t)},[]);return <div className="fixed top-4 right-4 pill z-40"><Clock size={14} className="inline mr-1"/>{String(Math.floor(s/60)).padStart(2,'0')}:{String(s%60).padStart(2,'0')}</div>}
function PresenterNotes({slide}:{slide:Slide}){return <div className="notes glass p-5 text-sm"><b>{slide.note.title}</b><p><b>Rôle:</b> {slide.note.purpose}</p><p><b>Durée:</b> {slide.note.duration}</p><p>{slide.note.scriptFR}</p><p><b>Phrase clé:</b> {slide.note.keySentence}</p><p><b>Question jury:</b> {slide.note.juryRisk}</p><p><b>Réponse:</b> {slide.note.shortAnswer}</p></div>}
function Navigation({prev,next,reset}:{prev:()=>void;next:()=>void;reset:()=>void}){return <div className="fixed bottom-5 left-1/2 -translate-x-1/2 flex gap-2 z-40"><button className="btn" onClick={prev}><ArrowLeft size={16}/></button><button className="btn" onClick={next}><ArrowRight size={16}/></button><button className="btn" onClick={reset}><RotateCcw size={16}/></button><span className="btn"><Maximize size={16}/></span><span className="btn"><NotebookTabs size={16}/></span><span className="btn"><Moon size={16}/></span></div>}
function SlideView({slide,index,total}:{slide:Slide;index:number;total:number}){const data=slide.data as any;return <motion.section className="slide" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-24}} transition={{duration:.45}}><div className="kicker">{slide.appendix?'Appendix':`Screen ${index+1} / ${total}`}</div><h1 className={slide.title.length>55?'smalltitle':'title'}>{slide.title}</h1>{slide.subtitle&&<p className="mt-4 text-2xl text-[#007A3D] font-semibold">{slide.subtitle}</p>}{slide.message&&<div className="glass p-6 my-6 text-2xl font-bold max-w-5xl">{slide.message}</div>}{['opening','issue','ar','vr','tunnel','positioning'].includes(slide.kind||'')&&<ThreeScene variant={slide.kind==='vr'?'vr':slide.kind==='tunnel'?'kpi':'module'}/>}<div className="mt-7 grid grid-cols-12 gap-5 pr-4">
{slide.bullets&&<div className="col-span-7 grid gap-3">{slide.bullets.map((b,i)=><Card key={b}><span className="pill mr-3">{i+1}</span><span className="text-xl font-semibold">{b}</span></Card>)}</div>}
{slide.columns&&slide.columns.map(c=><div className="col-span-6" key={c.title}><Card><h2 className="text-2xl font-black text-[#007A3D] mb-4">{c.title}</h2><ul className="space-y-2">{c.items.map(x=><li key={x}>• {x}</li>)}</ul></Card></div>)}
{slide.kind==='benchmark'&&<div className="col-span-12 grid grid-cols-4 gap-4">{data.actors.map((a:any)=><Card key={a[0]}><h3 className="font-black text-xl">{a[0]}</h3><p>{a[1]}</p></Card>)}</div>}
{slide.kind==='diagnosticMatrix'&&<div className="col-span-12 grid grid-cols-3 gap-4">{data.offers.map((o:any)=><Card key={o[0]}><h3 className="font-black text-2xl text-[#007A3D]">{o[0]}</h3><p className="font-bold mt-3">{o[1]}</p><p className="mt-2">{o[2]}</p></Card>)}</div>}
{slide.kind==='numbers'&&<div className="col-span-5 glass p-4"><MoneyBars data={data.proposals}/></div>}
{slide.kind==='benchmarkCards'&&<div className="col-span-12 grid grid-cols-4 gap-4">{data.rows.map((r:any)=><Card key={r[0]}><h3 className="font-black text-xl">{r[0]}</h3><p className="mt-2">{r[1]}</p><p className="mt-3 text-[#007A3D] font-bold">{r[2]}</p></Card>)}</div>}
{slide.kind==='segmentation'&&<div className="col-span-12 grid grid-cols-3 gap-4">{[['E-learning','large accounts; multi-site clients; specific internal processes; customization / standardization / scalability'],['AR','existing fire safety clients; SMEs; recurring B2B clients; upsell / visual impact / operational realism'],['VR','vehicle fleets; logistics; field teams; mobile employees; road risk prevention / realistic simulation']].map(x=><Card key={x[0]}><h3 className="text-3xl font-black text-[#007A3D]">{x[0]}</h3><p className="mt-4 text-lg">{x[1]}</p></Card>)}</div>}
{slide.kind==='actionPlan'&&<div className="col-span-5"><ThreeScene variant="kpi"/></div>}
{slide.kind==='timeline'&&<div className="col-span-12 grid grid-cols-6 gap-3">{['M1 Segment','M2 Email','M3 Call','M4 Demo','M5 Quote','M6 Review'].map(m=><Card key={m}><b>{m}</b><p className="text-sm mt-2">Hover-ready milestone for the pilot campaign.</p></Card>)}</div>}
{slide.kind==='kpi'&&<div className="col-span-12 grid grid-cols-5 gap-3">{slide.bullets?.map(k=><Card key={k}><p className="kicker">Recommended KPI</p><b>{k}</b></Card>)}</div>}
{slide.kind==='budget'&&<div className="col-span-12 grid grid-cols-2 gap-5"><Card><h2 className="text-2xl font-black">Direct budget: €4,800–€8,300</h2>{data.budget.map((b:any)=><p key={b[0]}>{b[0]}: {fmt(b[1])}–{fmt(b[2])}</p>)}</Card><Card><h2 className="text-2xl font-black">2025 signed revenue: {fmt(data.total)}</h2><MoneyBars data={data.baseline}/></Card></div>}
{slide.kind==='roi'&&<div className="col-span-12 grid grid-cols-3 gap-4">{data.scenarios.map((s:any)=><Card key={s[0]}><h3 className="text-2xl font-black">{s[0]}</h3><p className="text-3xl text-[#007A3D] font-black my-3">{fmt(s[1])}</p><p>Break-even margin: <b>{s[2]}</b></p></Card>)}</div>}
{slide.kind==='final'&&<div className="absolute right-16 bottom-20"><QR/></div>}
</div></motion.section>}
export default function App(){const[appendix,setAppendix]=useState(false);const[i,setI]=useState(0);const[notes,setNotes]=useState(false);const[timer,setTimer]=useState(true);const[black,setBlack]=useState(false);const slides=appendix?annexSlides:mainSlides;const clamp=(n:number)=>Math.max(0,Math.min(slides.length-1,n));const next=()=>setI(x=>clamp(x+1));const prev=()=>setI(x=>clamp(x-1));useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'||e.key===' ')next();if(e.key==='ArrowLeft')prev();if(e.key.toLowerCase()==='n')setNotes(x=>!x);if(e.key.toLowerCase()==='t')setTimer(x=>!x);if(e.key.toLowerCase()==='b')setBlack(x=>!x);if(e.key.toLowerCase()==='a'){setAppendix(x=>!x);setI(0)}if(e.key.toLowerCase()==='r'){setAppendix(false);setI(1)}if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.()};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[slides.length]);const slide=slides[i];return <main className="deck flex items-center justify-center"><AnimatePresence mode="wait"><SlideView key={(appendix?'a':'m')+slide.id} slide={slide} index={i} total={slides.length}/></AnimatePresence>{timer&&<Timer/>}{notes&&<PresenterNotes slide={slide}/>}<Navigation prev={prev} next={next} reset={()=>{setAppendix(false);setI(1)}}/><ProgressBar i={i} total={slides.length}/>{black&&<div className="black"/>}</main>}
