import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { financialBaseline, roiScenarios } from '../data/presentationContent';
import { formatEuro } from '../utils/format';
import TopicIllustration from './TopicIllustration';

const data = roiScenarios.map((s) => ({
  name: `${s.name} ${s.growth}`,
  'Additional revenue': s.additionalRevenue,
  'Additional margin': s.additionalMargin
}));

export default function RoiScenarioChart() {
  return (
    <div className="grid h-full grid-cols-[1fr_.95fr] gap-4">
      <div className="glass rounded-[1.5rem] p-4">
        <div className="mb-2 flex items-center justify-between">
          <div>
            <div className="kicker">Additional signed revenue x 35%</div>
            <div className="mt-1 text-sm font-bold text-fiducial-anthracite/60">Additional margin generated by each scenario</div>
          </div>
          <TopicIllustration variant="roi" size="sm" />
        </div>
        <ResponsiveContainer width="100%" height="82%">
          <BarChart data={data} margin={{ top: 12, right: 16, left: 0, bottom: 6 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(47,58,58,.12)" />
            <XAxis dataKey="name" tick={{ fontSize: 12 }} />
            <YAxis tickFormatter={(v) => `€${v / 1000}k`} tick={{ fontSize: 12 }} />
            <Tooltip formatter={(v) => formatEuro(Number(v))} />
            <Bar dataKey="Additional revenue" fill="#DFF3EA" radius={[10, 10, 0, 0]} />
            <Bar dataKey="Additional margin" fill="#007A3D" radius={[10, 10, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
      <div className="glass rounded-[1.5rem] p-4">
        <div className="kicker">ROI calculation</div>
        <div className="mt-2 grid gap-2 text-[11px] font-black text-fiducial-anthracite/70">
          <div className="rounded-2xl bg-white/75 p-2.5">Additional margin = Additional signed revenue x 35%</div>
          <div className="rounded-2xl bg-white/75 p-2.5">ROI = (Additional margin - {formatEuro(financialBaseline.budgetTotal)}) / {formatEuro(financialBaseline.budgetTotal)}</div>
        </div>
        <div className="mt-2.5 space-y-2">
          {roiScenarios.map((s) => {
            const active = s.name === 'Realistic';
            return (
              <div key={s.name} className={active ? 'rounded-2xl bg-fiducial-deep p-2.5 text-white shadow-xl' : 'rounded-2xl bg-white/75 p-2.5'}>
                <div className="flex items-center justify-between gap-3 text-sm font-black">
                  <span className="flex items-center gap-2"><TopicIllustration variant={s.name === 'Conservative' ? 'risk' : active ? 'conversion' : 'revenue'} size="xs" />{s.name} {s.growth}</span>
                  <span>ROI {s.roi > 0 ? '+' : ''}{s.roi.toFixed(1)}%</span>
                </div>
                <div className={active ? 'mt-2 grid grid-cols-2 gap-2 text-xs font-bold text-white/74' : 'mt-2 grid grid-cols-2 gap-2 text-xs font-bold text-fiducial-anthracite/55'}>
                  <span>Revenue: {formatEuro(s.additionalRevenue)}</span>
                  <span>Margin: {formatEuro(s.additionalMargin)}</span>
                </div>
              </div>
            );
          })}
        </div>
        <p className="mt-2 rounded-2xl bg-fiducial-mint p-2.5 text-[11px] font-black leading-snug text-fiducial-deep">The realistic scenario generates a positive ROI of +49.9%, with internal time included.</p>
      </div>
    </div>
  );
}
